### ISSUE TITLE
Multiple conflicting modules detected in pack manifest.

### ISSUE THREAD

**Issue by nick21500** [Ian1971/mcbuilderwand#2]
I'm sorry I don't have any more info to give but I've never seen this error message and it's completely unheard of by Google. I'm also sorry if I'm being stupid, I've never modded bedrock.

The resource pack works fine but trying to install the behavior pack returns [this](https://user-images.githubusercontent.com/45804088/167961801-3ec595d0-2cee-4cca-b37e-edc77e159b92.png)

**Comment by Ian1971** [comment]
hmm that's weird. It was working fine. I wonder if anything changed with the newer version of minecraft. What version do you have?

**Comment by Ian1971** [comment]
Hmmm I tried on latest and had the same problem. If I removed the client scripts module it installed, but it clearly won't function then. I know they are deprecating the client scripts ui, so I guess they removed it now. This is annoying because the replacement "GameTest Framework" can't do the same things as the old experimental scripting api. I'll have to see if they have added more to game test framework.

**Comment by nick21500** [comment]
Yeah 1.18.3 but you got it
I hope they have! bc cool mod :)

**Comment by Ian1971** [comment]
I checked the new documentation, it does look like it might be possible, not sure about the UI. I will have to carve out some time to give it a try.

**Comment by Ian1971** [comment]
Having some success. Sphere works, so now to figure out the UI

**Comment by Ian1971** [comment]
@nick21500 I've finished converting it to the gametest framework, so it should work again now. 
Let me know how you get on
[See 1.0.0](https://github.com/Ian1971/mcbuilderwand/releases/tag/1.0.0)

**Comment by nick21500** [comment]
I do see it now in the creative inventory! but right clicking a block doesn't do anything :o

**Comment by nick21500** [comment]
nope nope ignore that i just got it

**Comment by nick21500** [comment]
It works beautifully <3
